version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "MilesAway"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gyy76ishfzkh"
s3_prefix = "MilesAway"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
