AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  miles-away-backend

  SAM for miles-away-backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  # DynamoDB table to store item: { PublicKey: &lt;PUBLIC_KEY&gt;, Email: &lt;NAME&gt;, PrivateKey: &lt;PRIVATE_KEY&gt;}
  MilesAwayUsers:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MilesAwayUsers
      AttributeDefinitions:
        - AttributeName: Email
          AttributeType: S
      KeySchema:
        - AttributeName: Email
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CreateUserFunction
      CodeUri: create-user/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Timeout: 10
      Architectures:
        - x86_64
      Policies:
        # Give Create/Read/Update/Delete Permissions to the MilesAwayUsers
        - DynamoDBCrudPolicy:
            TableName: MilesAwayUsers
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          USERS_TABLE: MilesAwayUsers
      Events:
        CreateUser:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /create/user
            Method: post

  ProfileFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: ProfileFunction
      CodeUri: get-profile/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Timeout: 20
      Architectures:
        - x86_64
      Policies:
        # Give Create/Read/Update/Delete Permissions to the MilesAwayUsers
        - DynamoDBCrudPolicy:
            TableName: MilesAwayUsers
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          USERS_TABLE: MilesAwayUsers
          NFT_CONTRACT_ADRESS: '0xb3216a6ac47B075000B744004fD81F6173d242C6'
      Events:
        Profile:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /profile
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ProfileApi:
    Description: "API Gateway endpoint URL for Prod stage for  get profile function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/profile/"
  ProfileFunction:
    Description: "Get Profile Lambda Function ARN"
    Value: !GetAtt ProfileFunction.Arn
  ProfileFunctionIamRole:
    Description: "Implicit IAM Role created for Profile function"
    Value: !GetAtt ProfileFunctionRole.Arn
